// generated by Fast Light User Interface Designer (fluid) version 1.0401

#ifndef FSenseUI_h
#define FSenseUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *FSenseUI;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *FSenseMenuBar;
Fl_Double_Window* mainWindow();
#endif
